In [3]:
import pandas as pd

# 예시 데이터 생성
sales_data = pd.DataFrame({
    'product': ['노트북', '마우스', '키보드', '모니터', '스피커'],
    'price': [1200000, 25000, 80000, 350000, 120000],
    'quantity': [10, 50, 30, 15, 25],
    'category': ['전자제품', '주변기기', '주변기기', '전자제품', '주변기기']
})

sales_data

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기

In [4]:
# 1. 단일 컬럼 선택
product_series = sales_data['product']
print(product_series)

0    노트북
1    마우스
2    키보드
3    모니터
4    스피커
Name: product, dtype: str

In [5]:
# 2. 다중 컬럼 선택
price_quantity = sales_data[['product', 'price', 'quantity']]
price_quantity

  product    price  quantity
0     노트북  1200000        10
1     마우스    25000        50
2     키보드    80000        30
3     모니터   350000        15
4     스피커   120000        25

In [6]:
# 3. 행 슬라이싱 (첫 3개 행 선택)
first_three = sales_data[0:3]
first_three

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기

## 조건부 선택

In [7]:
# 1. 불리언 인덱싱
# df[조건식]
# 가격(price)이 100000원 이상인 제품 선택
# sales_data의 가격이 100000원 이상
# 조건식: sales_data['price'] >= 100000
expensive_products = sales_data[sales_data['price'] >= 100000]
expensive_products

  product    price  quantity category
0     노트북  1200000        10     전자제품
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기

In [8]:
# 2. df.query()
# high_quantity = sales_data[sales_data['quantity'] > 20]
high_quantity = sales_data.query('quantity > 20')
high_quantity

  product   price  quantity category
1     마우스   25000        50     주변기기
2     키보드   80000        30     주변기기
4     스피커  120000        25     주변기기

## loc과 iloc을 활용한 라벨/위치 기반 선택

In [9]:
# 인덱스 설정
sales_data_indexed = sales_data.set_index('product')
print(sales_data)
print(sales_data_indexed)

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기
           price  quantity category
product
노트북      1200000        10     전자제품
마우스        25000        50     주변기기
키보드        80000        30     주변기기
모니터       350000        15     전자제품
스피커       120000        25     주변기기

In [10]:
# 1. 특정 제품의 가격 선택
# df.loc[행라벨, 열라벨]: 라벨 기반 선택
notebook_info = sales_data_indexed.loc['노트북', 'price']
print(f'노트북 가격: {notebook_info:,}원')

노트북 가격: 1,200,000원

In [11]:
# 2. 여러 제품의 가격과 수량 선택
# df.loc[[행라벨, ...], [열라벨, ...]]: 라벨 기반 선택
selected_data = sales_data_indexed.loc[['노트북', '모니터'], ['price', 'quantity']]
selected_data

           price  quantity
product
노트북      1200000        10
모니터       350000        15

In [12]:
# 3. 첫 번째와 세 번째 행, 두 번째와 세 번째 컬럼
# df.iloc[행index, 열index]
# positional_data1 = sales_data.iloc[0:3, 1:3]
positional_data2 = sales_data.iloc[[0, 2], [1, 2]]
print(sales_data)
# print(positional_data1)
print(positional_data2)

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기
     price  quantity
0  1200000        10
2    80000        30

## 다중 조건 선택

In [13]:
# 1. 가격(price)이 50000원 이상이면서 수량(quantity)이 20개 이상인 제품
# 가격 >= 50000 & 수량 >= 20
# sales_data['price'] >= 50000 & sales_data['quantity'] >= 20
filtered_products = sales_data[(sales_data['price'] >= 50000) & (sales_data['quantity'] >= 20)]
print(sales_data)
print(f'\n{filtered_products}')

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기

  product   price  quantity category
2     키보드   80000        30     주변기기
4     스피커  120000        25     주변기기

In [14]:
# 2. 전자제품(category)이거나 가격(price)이 30000원 이하인 제품
# (sales_data['category'] == '전자제품') | (sales_data['price'] <= 30000)
electrnic_or_cheap = sales_data[(sales_data['category'] == '전자제품') | (sales_data['price'] <= 30000)]
print(sales_data)
print(f'\n{electrnic_or_cheap}')

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
3     모니터   350000        15     전자제품

## 그룹별 데이터 선택

In [15]:
# 카테고리별 그룹화 후 전자제품 구룹만 선택
# df.groupby('컬럼명').get_group(데이터)
electrnics_group = sales_data.groupby('category').get_group('전자제품')
print(electrnics_group)

  product    price  quantity category
0     노트북  1200000        10     전자제품
3     모니터   350000        15     전자제품

In [18]:
# 각 카테고리별 평균 가격을 원본 데이터에 추가
sales_data['category_avg_price'] = sales_data.groupby('category')['price'].transform('mean')
print(sales_data[['product', 'category', 'price', 'category_avg_price']])

  product category    price  category_avg_price
0     노트북     전자제품  1200000            775000.0
1     마우스     주변기기    25000             75000.0
2     키보드     주변기기    80000             75000.0
3     모니터     전자제품   350000            775000.0
4     스피커     주변기기   120000             75000.0

## 시계열 데이터 선택

In [32]:
# 시계열 데이터 생성
# pd.date_range('시작날짜', periods=기간, freq='D')
# freq:
# - 빈도 수 기준,
# - D(Day, 일), ME(Month End, 월말), MS(Month Start, 월초), W(Week, 주)
dates = pd.date_range('2026-01-01', periods=5, freq='D')
time_series_data = pd.DataFrame({
    'date': dates,
    'sales': [100, 150, 200, 120, 180],
    'returns': [5, 8, 12, 6, 9]
})
time_series_data.set_index('date', inplace=True)

print(time_series_data)

            sales  returns
date
2026-01-01    100        5
2026-01-02    150        8
2026-01-03    200       12
2026-01-04    120        6
2026-01-05    180        9

In [33]:
# 1. 특정 날짜 범위 선택
jan_1_to_3 = time_series_data.loc['2026-01-01':'2026-01-03']
print(jan_1_to_3)

            sales  returns
date
2026-01-01    100        5
2026-01-02    150        8
2026-01-03    200       12

In [39]:
# 2. 연도 기준 필터링
# 2026년 데이터만 선택
# df.index.year
# df.index.month
# df.index.day
year_2026 = time_series_data[time_series_data.index.year == 2026]
print(year_2026)

            sales  returns
date
2026-01-01    100        5
2026-01-02    150        8
2026-01-03    200       12
2026-01-04    120        6
2026-01-05    180        9