In [2]:
import pandas as pd

# 예시 데이터 생성
sales_data = pd.DataFrame({
    'product': ['노트북', '마우스', '키보드', '모니터', '스피커'],
    'price': [1200000, 25000, 80000, 350000, 120000],
    'quantity': [10, 50, 30, 15, 25],
    'category': ['전자제품', '주변기기', '주변기기', '전자제품', '주변기기']
})

sales_data

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기

In [4]:
# 1. 단일 컬럼 선택
product_series = sales_data['product']
print(product_series)

0    노트북
1    마우스
2    키보드
3    모니터
4    스피커
Name: product, dtype: str

In [7]:
# 2. 다중 컬럼 선택
price_quantity = sales_data[['product', 'price', 'quantity']]
price_quantity

  product    price  quantity
0     노트북  1200000        10
1     마우스    25000        50
2     키보드    80000        30
3     모니터   350000        15
4     스피커   120000        25

In [9]:
# 3. 행 슬라이싱 (첫 3개 행 선택)
first_three = sales_data[0:3]
first_three

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기

## 조건부 선택

In [11]:
# 1. 불리언 인덱싱
# df[조건식]
# 가격(price)이 100000원 이상인 제품 선택
# sales_data의 가격이 100000원 이상
# 조건식: sales_data['price'] >= 100000
expensive_products = sales_data[sales_data['price'] >= 100000]
expensive_products

  product    price  quantity category
0     노트북  1200000        10     전자제품
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기

In [17]:
# 2. df.query()
# high_quantity = sales_data[sales_data['quantity'] > 20]
high_quantity = sales_data.query('quantity > 20')
high_quantity

  product   price  quantity category
1     마우스   25000        50     주변기기
2     키보드   80000        30     주변기기
4     스피커  120000        25     주변기기

## loc과 iloc을 활용한 라벨/위치 기반 선택

In [20]:
# 인덱스 설정
sales_data_indexed = sales_data.set_index('product')
print(sales_data)
print(sales_data_indexed)

  product    price  quantity category
0     노트북  1200000        10     전자제품
1     마우스    25000        50     주변기기
2     키보드    80000        30     주변기기
3     모니터   350000        15     전자제품
4     스피커   120000        25     주변기기
           price  quantity category
product
노트북      1200000        10     전자제품
마우스        25000        50     주변기기
키보드        80000        30     주변기기
모니터       350000        15     전자제품
스피커       120000        25     주변기기