### 결측치 처리
결측치?  
데이터 수집 문제 또는 데이터 입력 오류와 같은 다양한 이유로 관측되어야 할 값을 얻지 못한 데이터

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 데이터프레임 생성
data = {
    'age': [25, np.nan, 30, 35, np.nan, 40],
    'salary': [50000, 55000, np.nan, 60000, 65000, np.nan],
    'height': [160, np.nan, 170, 175, 180, np.nan]
}

df = pd.DataFrame(data)
df

    age   salary  height
0  25.0  50000.0   160.0
1   NaN  55000.0     NaN
2  30.0      NaN   170.0
3  35.0  60000.0   175.0
4   NaN  65000.0   180.0
5  40.0      NaN     NaN

In [3]:
# age 컬럼의 결측치는 선형 보간법(Linear Interpolation)을 사용하여 처리
df['age'] = df['age'].interpolate(method='linear')
# salary 컬럼의 결측치는 평균값으로 대체
df['salary'] = df['salary'].fillna(df['salary'].mean())
# height 컬럼의 결측치는 중앙값으로 대체
df['height'] = df['height'].fillna(df['height'].median())
df

    age   salary  height
0  25.0  50000.0   160.0
1  27.5  55000.0   172.5
2  30.0  57500.0   170.0
3  35.0  60000.0   175.0
4  37.5  65000.0   180.0
5  40.0  57500.0   172.5

In [26]:
# 데이터프레임 생성
data2 = {
    'age': [25, np.nan, 30, 35, np.nan, 40],
    'salary': [50000, np.nan, np.nan, 60000, 65000, np.nan],
    'height': [160, np.nan, 170, 175, 180, np.nan]
}

df2 = pd.DataFrame(data2)
df2

    age   salary  height
0  25.0  50000.0   160.0
1   NaN      NaN     NaN
2  30.0      NaN   170.0
3  35.0  60000.0   175.0
4   NaN  65000.0   180.0
5  40.0      NaN     NaN

In [6]:
# 모든 컬럼에 결측치가 포함된 행 삭제
df2 = df2.dropna(how='all')
df2

    age   salary  height
0  25.0  50000.0   160.0
2  30.0      NaN   170.0
3  35.0  60000.0   175.0
4   NaN  65000.0   180.0
5  40.0      NaN     NaN

In [7]:
df2 = df2.dropna(axis=1)
df2

Empty DataFrame
Columns: []
Index: [0, 2, 3, 4, 5]

In [27]:
df2

    age   salary  height
0  25.0  50000.0   160.0
1   NaN      NaN     NaN
2  30.0      NaN   170.0
3  35.0  60000.0   175.0
4   NaN  65000.0   180.0
5  40.0      NaN     NaN

In [28]:
df2.dropna(subset=['salary'])

    age   salary  height
0  25.0  50000.0   160.0
3  35.0  60000.0   175.0
4   NaN  65000.0   180.0

In [29]:
df2

    age   salary  height
0  25.0  50000.0   160.0
1   NaN      NaN     NaN
2  30.0      NaN   170.0
3  35.0  60000.0   175.0
4   NaN  65000.0   180.0
5  40.0      NaN     NaN

In [ ]:
# inplace=True : "원본을 직접 바꿔!"
df2.dropna(subset=['salary'], inplace=True)

In [31]:
df2

    age   salary  height
0  25.0  50000.0   160.0
3  35.0  60000.0   175.0
4   NaN  65000.0   180.0