In [1]:
# 데이터 탐색 및 준비
import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs, make_classification, make_regression

# 변환(정규화, 표준화)
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# 축소
from sklearn.decomposition import PCA
# 분리(train, test)
from sklearn.model_selection import train_test_split

In [2]:
# 분류 데이터 생성
# X: 독립(입력)변수
# y: 종속(출력)변수
X, y = make_classification(n_samples=100, n_features=5, random_state=42)
print(X)
print(y)

[[-0.43066755  0.67287309 -0.72427983 -0.53963044 -0.65160035]
 [ 0.21164583 -0.84389686  0.53479393  0.82584805  0.68195297]
 [ 1.09267506  0.40910605  1.10009583 -0.94275087 -0.98150865]
 [ 1.51990078 -0.77336118  1.99805321  0.15513175 -0.3853136 ]
 [-0.45390127 -2.18347304  0.24472415  2.59123946 -0.48423407]
 [-1.46361184  0.37531604 -1.79532002  0.25415746 -1.24778318]
 [ 0.88948365  0.80742726  0.73019848 -1.28568005  0.13074058]
 [-1.11327862  1.89033108 -1.92487377 -1.5598485   0.18645431]
 [ 0.63174629 -0.88541844  1.02703224  0.68057323  0.54709738]
 [-0.88602706 -0.83311649 -0.7173148   1.31217492  0.44381943]
 [ 0.56372286 -1.47487037  1.15509316  1.35536951 -0.2176812 ]
 [-1.02754411 -0.32929388 -1.05383855  0.82600732 -0.05952536]
 [ 0.19375402 -0.96314239  0.55600276  0.96423311 -0.20219265]
 [-0.05396947  0.15985512 -0.11708689 -0.15013844  0.82541635]
 [ 0.96335953  0.65992405  0.86561977 -1.15806823  0.46210347]
 [-1.09939128 -0.47936995 -1.08324727  1.02255619 -0.92693047]
 [-0.64760425  1.34700796 -1.20592943 -1.17762637  0.85243333]
 [-1.37111696  0.50688537 -1.73597973  0.06845616  0.77463405]
 [ 1.30373602 -0.22210005  1.56010259 -0.34898484  0.06980208]
 [-0.52878508  0.94621814 -0.9311259  -0.79371387 -0.11473644]
 [ 1.7240021  -1.22823431  2.38869353  0.55942643 -1.43586215]
 [-0.56603681 -1.41693293 -0.14994102  1.80474148  1.03246526]
 [ 0.70385192 -1.29826331  1.25291095  1.09885263  1.09877685]
 [ 0.17593    -1.01695056  0.55448398  1.03110238  0.30729952]
 [ 0.04668349 -0.24878048  0.13979096  0.25058844  0.61037027]
 [-1.03260487 -0.62804104 -0.95548162  1.15466088 -0.47494531]
 [ 0.52576893 -0.82741596  0.88629356  0.66530077 -0.6929096 ]
 [-1.10644979 -0.32066954 -1.14658127  0.85239186 -1.43014138]
 [ 1.1374615   0.24412056  1.20852705 -0.78284083 -0.20812225]
 [-0.81296687  1.85571007 -1.57127256 -1.65830375 -0.47193187]
 [-0.83806958  1.89792447 -1.61453273 -1.69302842 -2.02514259]
 [ 1.17077461 -2.65461268  2.25661188  2.36867367 -0.56018104]
 [ 0.08714206  0.0291022   0.08896214 -0.07133524  0.08187414]
 [ 0.4057089  -0.46809422  0.62453032  0.32725188  1.30547881]
 [ 0.65574086  1.3939833   0.25995672 -1.82037691  0.66213067]
 [-0.87306613  1.65095783 -1.56826626 -1.40735658  0.04557184]
 [ 0.71768635  1.30857636  0.36016958 -1.75518644 -1.9520878 ]
 [ 0.55831966 -1.31089865  1.09180466  1.17869556 -0.02090159]
 [ 0.64701888  1.44901594  0.23085877 -1.87653774  2.13303337]
 [ 0.88439534 -2.68317954  1.94087643  2.52983424 -0.59157139]
 [ 1.13446163  0.26843823  1.19664076 -0.80804463  0.28099187]
 [ 0.55253544  1.6253749   0.06194498 -2.02632079 -0.49300093]
 [-0.79383636  1.74355119 -1.51042899 -1.54446032  0.67959775]
 [ 1.306542   -0.23938468  1.56931739 -0.3313761   0.58831721]
 [ 0.28247903 -1.19137182  0.73644435  1.17329352  0.81286212]
 [ 0.97687358 -1.80921926  1.74147706  1.53313849 -0.82899501]
 [-1.13714057 -0.24038388 -1.20946429  0.77861318  1.26691115]
 [-1.45612516  2.48904785 -2.52343407 -2.05832072  1.0889506 ]
 [-1.03398089 -0.56156012 -0.98021491  1.08266027  1.76545424]
 [-0.84321213 -0.70426956 -0.71352532  1.15199146 -0.33450124]
 [-0.69102126 -1.22532865 -0.35885569  1.65214494  0.91786195]
 [-1.29267194 -0.1173572  -1.42922002  0.71479373  0.40498171]
 [-1.69200458  0.95057302 -2.25553963 -0.27062383 -0.70766947]
 [ 1.33970234 -2.24075406  2.30450019  1.83991037  0.89959988]
 [ 1.46098002 -0.55818081  1.85605469 -0.05319823 -0.60021688]
 [ 0.36783185 -0.21800395  0.49429823  0.07123641 -1.86726519]
 [-0.7635164   1.43140126 -1.36716377 -1.21722043 -0.73036663]
 [-0.79864786 -1.07525068 -0.53355799  1.53703587 -3.24126734]
 [ 0.50230075  1.77872961 -0.04862909 -2.17105282 -0.44004449]
 [ 0.68720469 -1.45724683  1.28938375  1.28008347  0.8496021 ]
 [ 0.36205368 -0.46281432  0.57304248  0.34129395 -0.31026676]
 [-0.94116325  1.63631177 -1.64060704 -1.36045573  0.06428002]
 [-0.99325144  1.69607038 -1.72067112 -1.40210053  0.21645859]
 [ 1.22541983  0.01066604  1.38991764 -0.56772453 -0.58936476]
 [-0.756006    1.62748917 -1.42695838 -1.43483867  2.14394409]
 [-0.51103632 -1.60499282 -0.02185231  1.98522348 -1.51936997]
 [ 0.44205183  1.94742094 -0.17593681 -2.3279946  -0.62269952]
 [-1.3731412   2.40437346 -2.39955005 -2.00347738 -0.79252074]
 [ 0.97650004  0.63067073  0.89075877 -1.13207427  1.44127329]
 [-0.68933585  1.39175475 -1.26898369 -1.20757158  2.31465857]
 [ 0.78025563 -2.0302233   1.59488828  1.86378908  1.2776649 ]
 [ 0.50047696 -1.46447269  1.07954187  1.3727107   0.81350964]
 [ 0.6635226  -1.44723231  1.25896077  1.2798899   0.02100384]
 [ 1.12210055  0.254643    1.18739045 -0.78736523  1.16316375]
 [-0.14951801  0.58846525 -0.3751207  -0.57500215 -0.66178646]
 [-0.32683618  0.8834691  -0.6795874  -0.81680628 -0.48536355]
 [ 0.77813969 -1.76254901  1.4991983   1.57233676  0.11732738]
 [ 0.30446853 -0.9809438   0.68811892  0.93343952  0.35701549]
 [ 0.30877317 -0.56811307  0.54914434  0.480502    0.74729361]
 [-0.74920203 -1.20727346 -0.43131517  1.65882246 -1.20029641]
 [ 0.99630897  0.53104737  0.94800532 -1.03223274  0.1990597 ]
 [ 1.28131775 -0.06692233  1.48052803 -0.50833095  0.11351735]
 [-1.19300559 -0.07873421 -1.32933233  0.6273745   0.86575519]
 [ 0.1094067   0.30759353  0.01722979 -0.38566776 -0.71530371]
 [-0.97763681 -0.54561186 -0.92169432  1.03967019  1.6324113 ]
 [-0.39769634  1.17059844 -0.86023823 -1.09831681  0.63391902]
 [ 1.05688647  0.40238353  1.06173727 -0.91916686  1.58601682]
 [-0.67826129 -1.09662143 -0.38919817  1.50575249 -1.26088395]
 [-0.63922566  1.18674111 -1.14054824 -1.00634985  0.68626019]
 [-0.74717988 -1.03371682 -0.48949935  1.46830827 -0.65332923]
 [ 0.32423734  2.23245441 -0.40925706 -2.58590856  0.01023306]
 [-1.24868955  2.35790248 -2.24181979 -2.00918545 -1.07774478]
 [ 0.46093758  1.89691056 -0.1368559  -2.2813861  -1.2378155 ]
 [-0.73426524  1.72251306 -1.43534875 -1.54851014  0.50498728]
 [-1.05463759 -0.55658056 -1.00544254  1.08659413 -0.25256815]
 [ 0.73594772  1.2031659   0.4176729  -1.64832073 -0.1517851 ]
 [ 0.84609208 -1.14052601  1.35970566  0.86199147  0.62962884]
 [-0.84467713  1.6431949  -1.5332749  -1.4117586  -1.61271587]
 [-1.2827436   0.12037048 -1.50077611  0.4505902   2.1221562 ]
 [-0.72216846 -1.12868571 -0.42795824  1.56070438 -1.02438764]]
[0 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 0 0
 1 0 1 0 0 0 0 1 1 1 0 1 1 1 1 1 1 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 1 1 1 0
 0 0 1 1 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 1 0 1 1]

In [3]:
X.shape

(100, 5)

In [4]:
df = pd.DataFrame(X, columns=[f'feature_{i+1}' for i in range(X.shape[1])])
df

    feature_1  feature_2  feature_3  feature_4  feature_5
0   -0.430668   0.672873  -0.724280  -0.539630  -0.651600
1    0.211646  -0.843897   0.534794   0.825848   0.681953
2    1.092675   0.409106   1.100096  -0.942751  -0.981509
3    1.519901  -0.773361   1.998053   0.155132  -0.385314
4   -0.453901  -2.183473   0.244724   2.591239  -0.484234
..        ...        ...        ...        ...        ...
95   0.735948   1.203166   0.417673  -1.648321  -0.151785
96   0.846092  -1.140526   1.359706   0.861991   0.629629
97  -0.844677   1.643195  -1.533275  -1.411759  -1.612716
98  -1.282744   0.120370  -1.500776   0.450590   2.122156
99  -0.722168  -1.128686  -0.427958   1.560704  -1.024388

[100 rows x 5 columns]

In [5]:
df['target'] = y
df

    feature_1  feature_2  feature_3  feature_4  feature_5  target
0   -0.430668   0.672873  -0.724280  -0.539630  -0.651600       0
1    0.211646  -0.843897   0.534794   0.825848   0.681953       1
2    1.092675   0.409106   1.100096  -0.942751  -0.981509       0
3    1.519901  -0.773361   1.998053   0.155132  -0.385314       0
4   -0.453901  -2.183473   0.244724   2.591239  -0.484234       1
..        ...        ...        ...        ...        ...     ...
95   0.735948   1.203166   0.417673  -1.648321  -0.151785       0
96   0.846092  -1.140526   1.359706   0.861991   0.629629       1
97  -0.844677   1.643195  -1.533275  -1.411759  -1.612716       0
98  -1.282744   0.120370  -1.500776   0.450590   2.122156       1
99  -0.722168  -1.128686  -0.427958   1.560704  -1.024388       1

[100 rows x 6 columns]

In [6]:
# 분류 데이터 생성 -> 결측치 데이터 추가
def create_classification_data():
    X, y = make_classification(n_samples=100, n_features=5, random_state=42)
    df = pd.DataFrame(X, columns=[f'feature_{i+1}' for i in range(X.shape[1])])
    df['target'] = y
    
    # feature_1에 결측치를 추가 (10% 비율로)
    # replace=False: 중복 없이
    missing_indices = np.random.choice(df.index, size=int(len(df) * 0.1), replace=False)
    df.loc[missing_indices, 'feature_1'] = np.nan
    
    return df

In [7]:
create_classification_data()

    feature_1  feature_2  feature_3  feature_4  feature_5  target
0   -0.430668   0.672873  -0.724280  -0.539630  -0.651600       0
1    0.211646  -0.843897   0.534794   0.825848   0.681953       1
2    1.092675   0.409106   1.100096  -0.942751  -0.981509       0
3    1.519901  -0.773361   1.998053   0.155132  -0.385314       0
4   -0.453901  -2.183473   0.244724   2.591239  -0.484234       1
..        ...        ...        ...        ...        ...     ...
95   0.735948   1.203166   0.417673  -1.648321  -0.151785       0
96   0.846092  -1.140526   1.359706   0.861991   0.629629       1
97  -0.844677   1.643195  -1.533275  -1.411759  -1.612716       0
98  -1.282744   0.120370  -1.500776   0.450590   2.122156       1
99        NaN  -1.128686  -0.427958   1.560704  -1.024388       1

[100 rows x 6 columns]

In [8]:
X, y = make_regression(n_samples=100, n_features=5, noise=0.1, random_state=42)
print(X)
print(y)

[[ 0.97511973 -0.67716171 -0.01224677 -0.89725437  0.07580456]
 [ 0.08187414 -0.48536355  0.75896922 -0.77282521 -0.23681861]
 [-1.4123037  -0.90802408 -0.56228753 -1.01283112  0.31424733]
 [-0.64511975  0.36163603  1.35624003 -0.07201012  1.0035329 ]
 [-0.62269952  0.28099187 -1.9520878  -0.1517851   0.58831721]
 [-0.45006547  0.04698059 -1.59442766 -0.59937502  0.0052437 ]
 [ 0.77463405  0.44381943 -0.48423407  1.26691115 -0.70766947]
 [ 0.35701549  0.8496021  -0.20812225 -0.49300093 -0.58936476]
 [-1.3044695  -0.08912004  0.38406545 -0.03269475 -2.0674421 ]
 [ 0.17318093 -1.24573878 -0.44651495  0.85639879  0.21409374]
 [ 0.29698467  0.52194157  0.78182287 -1.23695071 -1.32045661]
 [-1.72491783 -1.91328024 -0.46341769 -0.46572975  0.24196227]
 [-1.98756891  0.09176078  0.8219025   0.08704707 -0.29900735]
 [-0.0555477  -1.70338244  0.07409478  1.62861555 -1.38010146]
 [ 0.65655361 -1.1913035  -0.71435142  1.86577451  0.47383292]
 [-0.01901621 -0.15993853  0.31090757  1.47535622  0.85765962]
 [-0.39210815 -0.32766215  0.09707755  0.96864499 -0.70205309]
 [ 0.19686124 -1.32818605 -1.22084365  0.2088636  -1.95967012]
 [-1.23086432  0.81351722  1.54993441 -0.78325329 -0.32206152]
 [ 1.50235705  0.71754226 -1.18325851 -2.03923218 -0.26940683]
 [ 1.52312408 -0.8612842  -0.00797264  1.47994414  0.07736831]
 [ 0.96337613 -0.82068232 -0.97468167  0.7870846   1.15859558]
 [-1.20029641  0.86575519 -0.79252074 -0.11473644  0.50498728]
 [-0.57690366  0.95042384  0.15039379  0.34175598  1.87617084]
 [-1.00601738  2.09238728  0.09699596  0.59515703 -0.81822068]
 [ 3.85273149  0.51504769 -0.93782504  0.51503527  0.51378595]
 [-0.3853136   0.06980208  0.46210347  0.1990597  -0.60021688]
 [-0.07444592  0.25755039  0.40405086  1.8861859   0.17457781]
 [-1.38279973 -0.87561825  0.53891004 -1.03724615 -0.19033868]
 [ 2.15318246  0.95927083  0.02451017  0.49799829  1.45114361]
 [-0.47193187 -1.61271587  2.31465857 -1.86726519  0.68626019]
 [-0.13014305  0.32416635  0.02100384  0.68195297 -0.31026676]
 [ 1.23781631 -0.11453985 -0.46917565 -1.71313453  1.35387237]
 [ 1.64496771  1.36687427 -0.2750517  -2.30192116 -1.51519106]
 [ 0.06751848  1.17929718 -0.74848654  1.55115198  0.11567463]
 [ 0.85243333 -0.66178646  0.63391902 -2.02514259  0.18645431]
 [ 0.75193303  1.14282281  0.30154734 -0.03471177 -1.16867804]
 [-0.8084936  -0.51827022 -0.21967189  0.35711257  1.47789404]
 [ 0.40498171  1.76545424 -0.33450124 -0.47494531 -0.65332923]
 [-0.75373616 -0.24538812  0.41278093  0.82206016  1.89679298]
 [-0.91942423  0.47359243 -1.55066343  0.06856297 -1.06230371]
 [ 0.51326743 -0.5297602  -0.50175704  0.91540212  0.32875111]
 [ 0.82254491 -1.05771093 -0.60170661  1.85227818 -0.01349722]
 [ 0.54256004 -0.46947439 -0.23413696  1.57921282  0.76743473]
 [ 1.11957491  3.07888081 -0.24903604  0.57655696  0.31125015]
 [ 1.17944012  1.83145877 -0.89841467  0.49191917 -1.32023321]
 [ 0.64537595  0.97157095  2.06074792  1.75534084 -0.24896415]
 [ 0.58685709 -1.40185106  0.79103195 -0.90938745  1.40279431]
 [ 0.2766908   0.34115197 -0.88951443 -0.81581028 -0.07710171]
 [ 0.69014399  0.40171172  0.51934651  1.53273891 -0.10876015]
 [-0.50347565  0.09965137  2.19045563 -0.99053633 -0.56629773]
 [-1.76304016  0.34361829 -0.71984421 -0.46063877  1.05712223]
 [-0.02090159  0.61037027 -0.82899501 -0.56018104  0.74729361]
 [-0.25256815 -1.02438764 -0.92693047 -0.05952536 -3.24126734]
 [-0.75913266 -0.52575502 -0.83972184 -0.59939265 -2.12389572]
 [-1.19787789 -0.55364931 -0.79287283 -0.10703036 -1.03524232]
 [-1.75873949  1.05842449  1.36863156 -0.96492346  0.68605146]
 [-2.6197451   1.56464366  0.36139561  1.53803657 -0.03582604]
 [-0.75635075  0.20346364 -0.12791759 -0.95554044 -1.60644632]
 [ 0.33231401  1.27767682  0.71161488 -1.12464209 -1.53411417]
 [-0.98150865  0.01023306  1.44127329 -1.43586215  1.16316375]
 [ 0.62834551  0.62411982 -1.21418861  1.15811087  0.79166269]
 [ 1.30547881  0.81350964 -0.2176812   1.09877685  0.82541635]
 [-0.21344715 -0.71844422  0.23204994 -1.44808434 -1.40746377]
 [ 2.13303337 -1.2378155   0.11351735  0.66213067  1.58601682]
 [ 0.13074058 -0.44004449 -1.24778318  1.6324113  -1.43014138]
 [ 2.72016917 -0.26465683  0.82718325  0.01300189  1.45353408]
 [-0.16128571 -0.80227727 -1.41537074 -0.42064532 -0.34271452]
 [-0.53025762  0.50404652 -0.0626791   0.95514232 -0.98572605]
 [-0.23415337  1.52302986  0.49671415 -0.1382643   0.64768854]
 [-0.11232805  0.21397991  1.96472513  0.03526355 -0.69972551]
 [ 0.88163976  1.68714164 -1.42225371 -0.64657288 -1.081548  ]
 [-1.37766937  1.05380205  0.35778736  0.56078453  1.08305124]
 [-1.1429703   0.05820872  0.38531738 -0.88385744  0.15372511]
 [ 0.25988279  0.18463386  0.22745993  1.30714275 -1.60748323]
 [-1.51936997  1.03246526 -1.26088395  0.91786195  2.1221562 ]
 [-1.47852199 -0.3011037   0.73846658  0.17136828 -0.11564828]
 [ 0.29307247  0.2322537   0.25049285  0.34644821 -0.68002472]
 [-0.57581824 -0.53050115 -0.2209696   0.6141667   0.75750771]
 [-0.22346279  0.48247242  0.62566735 -0.85715756 -1.0708925 ]
 [-0.54438272 -1.42474819  1.46564877 -0.2257763   0.0675282 ]
 [-0.56372455  0.41293145 -0.14705738 -0.8254972  -0.32138584]
 [-0.80829829  2.18980293 -0.76734756  0.87232064  0.18334201]
 [-0.31526924  0.65139125  0.57089051  1.13556564  0.95400176]
 [ 0.62962884  0.81286212 -0.6929096   0.89959988  0.30729952]
 [ 0.51443883  0.12029563  0.62284993 -1.06762043 -0.14237949]
 [-0.20219265  0.54709738  0.11732738  1.2776649  -0.59157139]
 [ 0.81252582 -1.19620662 -0.47917424 -0.18565898 -1.10633497]
 [ 0.97554513  0.33126343  0.93128012 -0.83921752 -0.30921238]
 [ 0.67959775 -0.71530371  1.0889506   0.06428002 -1.07774478]
 [-1.05921352 -0.51386692  0.66967255  0.36659825 -0.93987979]
 [ 2.14394409 -0.65160035 -0.73036663  0.21645859  0.04557184]
 [-0.19236096  2.46324211 -1.91877122 -0.02651388  0.06023021]
 [-0.82723094  0.32271856 -1.00252936 -0.01851314 -0.28865864]
 [-0.29169375 -0.60063869  0.11092259 -1.15099358  0.37569802]
 [-1.51484722 -0.84679372  0.71400049  0.47323762 -0.07282891]
 [-0.77300978  0.0976761  -0.40122047  0.22409248  0.0125924 ]
 [ 1.03099952  0.61167629  0.32408397 -0.38508228 -0.676922  ]
 [-0.23458713  0.00511346 -1.46351495  0.29612028  0.26105527]
 [-0.47103831 -0.50694318 -0.8222204   0.24368721  0.24496657]]
[-5.71957602e+01 -4.65464769e+01 -2.58133440e+02  1.15850751e+02
 -1.23767712e+02 -1.59543665e+02  1.06602825e+02  4.28451365e+01
 -1.38527690e+02 -8.46285101e+01  2.43648528e+00 -3.41184598e+02
 -6.39938337e+01 -1.22767221e+02 -4.98561274e-01  1.17992273e+02
 -1.93142829e+01 -2.55874865e+02  4.95994132e+01 -4.04705231e+01
  9.38488938e+01  9.01636909e-01 -2.70716053e+01  1.54804066e+02
  1.56679193e+02  2.71559506e+02  3.48467597e+00  1.60796219e+02
 -2.01292034e+02  3.06766986e+02 -1.20302509e+02  5.31053063e+01
 -1.60669169e+01  3.14784308e+01  1.64779437e+02 -8.14952111e+01
  1.34071166e+02 -4.12302744e+01  1.26729199e+02  7.10993680e+01
 -1.43096538e+02  1.03980808e+01  1.17781661e+01  8.88715389e+01
  3.99561141e+02  1.75209105e+02  3.59265843e+02 -5.35751438e+01
 -5.63639791e+01  1.98506163e+02  4.38393406e+01 -1.07978065e+02
  1.35243456e-02 -2.95079278e+02 -2.62022705e+02 -2.21413963e+02
  5.55500822e+01  1.05439723e+02 -1.45614856e+02  7.32697712e+01
 -5.83515656e+00  1.15416375e+02  2.37317144e+02 -2.01507730e+02
  1.08483397e+02 -7.38718680e+01  2.44562637e+02 -2.16457568e+02
  3.30995023e+01  1.83284428e+02  1.18262908e+02  5.26631047e+01
  1.14116671e+02 -8.35049702e+01  6.58639781e+01  5.62714015e+01
 -6.61577920e+01  5.22906792e+01 -3.95145339e+01 -1.26462624e+01
 -8.93824900e+01 -6.14718144e+01  1.73874234e+02  1.80647615e+02
  1.35959998e+02  1.72623685e+01  1.01292829e+02 -1.49707035e+02
  9.30085406e+01  6.23947999e+00 -8.40642035e+01  3.24443158e+01
  1.07988075e+02 -9.43561568e+01 -1.22118392e+02 -1.04690611e+02
 -4.98387941e+01  9.76856893e+01 -8.18772444e+01 -1.09045266e+02]

In [9]:
df = pd.DataFrame(X, columns=[f'feature_{i+1}' for i in range(X.shape[1])])
df['target'] = y
df

    feature_1  feature_2  feature_3  feature_4  feature_5      target
0    0.975120  -0.677162  -0.012247  -0.897254   0.075805  -57.195760
1    0.081874  -0.485364   0.758969  -0.772825  -0.236819  -46.546477
2   -1.412304  -0.908024  -0.562288  -1.012831   0.314247 -258.133440
3   -0.645120   0.361636   1.356240  -0.072010   1.003533  115.850751
4   -0.622700   0.280992  -1.952088  -0.151785   0.588317 -123.767712
..        ...        ...        ...        ...        ...         ...
95  -1.514847  -0.846794   0.714000   0.473238  -0.072829 -104.690611
96  -0.773010   0.097676  -0.401220   0.224092   0.012592  -49.838794
97   1.031000   0.611676   0.324084  -0.385082  -0.676922   97.685689
98  -0.234587   0.005113  -1.463515   0.296120   0.261055  -81.877244
99  -0.471038  -0.506943  -0.822220   0.243687   0.244967 -109.045266

[100 rows x 6 columns]

In [10]:
for column in df.columns[:-1]:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    # 하한선
    lower_bound = Q1 - 1.5 * IQR
    # 상한선
    upper_bound = Q3 + 1.5 * IQR

    print('Q1: ', Q1)
    print('Q3: ', Q3)
    print('IQR: ', IQR)
    print('lower_bound: ', lower_bound)
    print('upper_bound: ', upper_bound)

Q1:  -0.757046224351652
Q3:  0.6481703643473181
IQR:  1.4052165886989703
lower_bound:  -2.8648711074001074
upper_bound:  2.7559952473957736
Q1:  -0.5362881870446912
Q3:  0.6679290024283391
IQR:  1.2042171894730302
lower_bound:  -2.3426139712542366
upper_bound:  2.474254786637885
Q1:  -0.734896607926991
Q3:  0.5242373966020439
IQR:  1.259134004529035
lower_bound:  -2.623597614720543
upper_bound:  2.4129384033955965
Q1:  -0.6781359668162878
Q3:  0.8306448185767356
IQR:  1.5087807853930233
lower_bound:  -2.9413071449058226
upper_bound:  3.0938159966662706
Q1:  -0.7003074044637773
Q3:  0.5324187648053007
IQR:  1.2327261692690779
lower_bound:  -2.549396658367394
upper_bound:  2.3815080187089173

In [11]:
# 회귀 데이터 생성 -> 이상치 데이터 추가
def create_regression_data():
    X, y = make_regression(n_samples=100, n_features=5, noise=0.1, random_state=42)
    df = pd.DataFrame(X, columns=[f'feature_{i+1}' for i in range(X.shape[1])])
    df['target'] = y

    # IQR(Interquartile Range): 이상치 포함여부 판단
    for column in df.columns[:-1]:
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1

        # 하한선
        lower_bound = Q1 - 1.5 * IQR
        # 상한선
        upper_bound = Q3 + 1.5 * IQR

        # 이상치를 추가할 인덱스를 랜덤하게 선택
        outlier_indices = np.random.choice(df.index, size=5, replace=False)
        for idx in outlier_indices:
            # at[행, 열]
            df.at[idx, column] = np.random.uniform(upper_bound + 1, upper_bound + 10)

    return df

In [12]:
create_regression_data()

    feature_1  feature_2  feature_3  feature_4  feature_5      target
0    0.975120  -0.677162  -0.012247  -0.897254   0.075805  -57.195760
1    0.081874  -0.485364   0.758969  -0.772825  -0.236819  -46.546477
2   -1.412304  -0.908024   7.625484   4.708727   0.314247 -258.133440
3   -0.645120   0.361636   1.356240  -0.072010   1.003533  115.850751
4   -0.622700   0.280992  -1.952088  -0.151785   0.588317 -123.767712
..        ...        ...        ...        ...        ...         ...
95  -1.514847  -0.846794   0.714000   0.473238  -0.072829 -104.690611
96   6.707093   0.097676  -0.401220   0.224092   0.012592  -49.838794
97   1.031000   0.611676   0.324084  -0.385082  -0.676922   97.685689
98  -0.234587   0.005113  -1.463515   0.296120   0.261055  -81.877244
99  -0.471038  -0.506943  -0.822220   0.243687   0.244967 -109.045266

[100 rows x 6 columns]

In [13]:
# 군집 데이터 생성 함수
def create_blobs_data():
    X, y = make_blobs(n_samples=100, n_features=5, centers=3, random_state=42)
    df = pd.DataFrame(X, columns=[f'feature_{i+1}' for i in range(X.shape[1])])
    df['target'] = y
    
    return df

In [14]:
create_blobs_data()

    feature_1  feature_2  feature_3  feature_4  feature_5  target
0   -3.002630   9.937449   6.346484   2.846759  -6.870483       0
1   -5.970371  -9.040785   7.384420   2.669463   4.287546       1
2   -2.290559   9.896047   3.630793   0.389875  -6.105927       0
3   -3.463695   8.263107   3.509451   2.743147  -5.611238       0
4   -1.888649   8.853349   4.251614   1.087657  -7.236372       0
..        ...        ...        ...        ...        ...     ...
95  -5.813911  -9.797336   8.705528   2.927422   3.557547       1
96  -2.334365   7.797431   5.689226   3.298275  -6.145126       0
97  -3.138673   9.612007   7.199367   2.367403  -6.757408       0
98  -1.927075   9.902035   5.534211   2.728167  -7.086793       0
99  -8.777487  -7.557787   6.708389   4.133618   4.848300       1

[100 rows x 6 columns]

In [15]:
# Generate datasets for each problem type
classification_df = create_classification_data()
regression_df = create_regression_data()
blobs_df = create_blobs_data()

In [16]:
print('=== Classification Generated Datasets ===')
print(classification_df.head())
print('\n=== regression Generated Datasets ===')
print(regression_df.head())
print('\n=== blobs Generated Datasets ===')
print(blobs_df.head())

=== Classification Generated Datasets ===
   feature_1  feature_2  feature_3  feature_4  feature_5  target
0  -0.430668   0.672873  -0.724280  -0.539630  -0.651600       0
1   0.211646  -0.843897   0.534794   0.825848   0.681953       1
2   1.092675   0.409106   1.100096  -0.942751  -0.981509       0
3   1.519901  -0.773361   1.998053   0.155132  -0.385314       0
4  -0.453901  -2.183473   0.244724   2.591239  -0.484234       1

=== regression Generated Datasets ===
   feature_1  feature_2  feature_3  feature_4  feature_5      target
0   0.975120  -0.677162  -0.012247  -0.897254   0.075805  -57.195760
1   0.081874  -0.485364   0.758969  -0.772825  -0.236819  -46.546477
2  -1.412304  -0.908024  -0.562288  -1.012831   0.314247 -258.133440
3  -0.645120   0.361636   1.356240  -0.072010   1.003533  115.850751
4  -0.622700   0.280992  -1.952088  -0.151785   0.588317 -123.767712

=== blobs Generated Datasets ===
   feature_1  feature_2  feature_3  feature_4  feature_5  target
0  -3.002630   9.937449   6.346484   2.846759  -6.870483       0
1  -5.970371  -9.040785   7.384420   2.669463   4.287546       1
2  -2.290559   9.896047   3.630793   0.389875  -6.105927       0
3  -3.463695   8.263107   3.509451   2.743147  -5.611238       0
4  -1.888649   8.853349   4.251614   1.087657  -7.236372       0

## 데이터 정제
### 1. 결측치 제거

In [17]:
# 결측치 확인
classification_df.isna()

    feature_1  feature_2  feature_3  feature_4  feature_5  target
0       False      False      False      False      False   False
1       False      False      False      False      False   False
2       False      False      False      False      False   False
3       False      False      False      False      False   False
4       False      False      False      False      False   False
..        ...        ...        ...        ...        ...     ...
95      False      False      False      False      False   False
96      False      False      False      False      False   False
97      False      False      False      False      False   False
98      False      False      False      False      False   False
99      False      False      False      False      False   False

[100 rows x 6 columns]

In [18]:
print('[전처리 전] 결측치 수:', classification_df.isna().sum())

[전처리 전] 결측치 수: feature_1    10
feature_2     0
feature_3     0
feature_4     0
feature_5     0
target        0
dtype: int64

In [19]:
print('[전처리 전] 결측치 수:', classification_df.isna().sum().sum())

[전처리 전] 결측치 수: 10

In [20]:
# 결측치를 feature_1의 평균값으로 변경
classification_df['feature_1'] = classification_df['feature_1'].fillna(classification_df['feature_1'].mean())
print('[전처리 후] 결측치 수:', classification_df.isna().sum().sum())

[전처리 후] 결측치 수: 0

### 2. 이상치 제거

In [21]:
print('이상치 처리 전 결측치 수:', regression_df['feature_3'].isna().sum())

이상치 처리 전 결측치 수: 0

In [22]:
# IQR
Q1 = regression_df['feature_3'].quantile(0.25)
Q3 = regression_df['feature_3'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# 이상치를 결측치로 변환
regression_df.loc[(regression_df['feature_3'] < lower_bound) | (regression_df['feature_3'] > upper_bound), 'feature_3'] = None

print('이상치 처리 후 결측치 수:', regression_df['feature_3'].isna().sum())

이상치 처리 후 결측치 수: 5

In [23]:
regression_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature_1  100 non-null    float64
 1   feature_2  100 non-null    float64
 2   feature_3  95 non-null     float64
 3   feature_4  100 non-null    float64
 4   feature_5  100 non-null    float64
 5   target     100 non-null    float64
dtypes: float64(6)
memory usage: 4.8 KB

In [24]:
regression_df.dropna(subset=['feature_3'], inplace=True)
print('결측치 삭제:', regression_df['feature_3'].isna().sum())

결측치 삭제: 0

In [25]:
regression_df.info()

<class 'pandas.DataFrame'>
Index: 95 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature_1  95 non-null     float64
 1   feature_2  95 non-null     float64
 2   feature_3  95 non-null     float64
 3   feature_4  95 non-null     float64
 4   feature_5  95 non-null     float64
 5   target     95 non-null     float64
dtypes: float64(6)
memory usage: 5.2 KB

## 데이터 통합

In [26]:
# 수평 결합
# axis=1: 결합의 축을 열(Column) 방향
pd.concat([classification_df, regression_df], axis=1)

,feature_1,feature_2,feature_3,feature_4,feature_5,target,feature_1,feature_2,feature_3,feature_4,feature_5,target
0,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,0.975120,-0.677162,-0.012247,-0.897254,0.075805,-57.195760
1,0.211646,-0.843897,0.534794,0.825848,0.681953,1,0.081874,-0.485364,0.758969,-0.772825,-0.236819,-46.546477
2,1.092675,0.409106,1.100096,-0.942751,-0.981509,0,-1.412304,-0.908024,-0.562288,-1.012831,0.314247,-258.133440
3,1.519901,-0.773361,1.998053,0.155132,-0.385314,0,-0.645120,0.361636,1.356240,-0.072010,1.003533,115.850751
4,-0.453901,-2.183473,0.244724,2.591239,-0.484234,1,-0.622700,0.280992,-1.952088,-0.151785,0.588317,-123.767712
...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.735948,1.203166,0.417673,-1.648321,-0.151785,0,-1.514847,-0.846794,0.714000,0.473238,4.025765,-104.690611
96,0.846092,-1.140526,1.359706,0.861991,0.629629,1,-0.773010,0.097676,-0.401220,0.224092,0.012592,-49.838794
97,-0.844677,1.643195,-1.533275,-1.411759,-1.612716,0,1.031000,0.611676,0.324084,-0.385082,-0.676922,97.685689
98,-1.282744,0.120370,-1.500776,0.450590,2.122156,1,-0.234587,0.005113,-1.463515,0.296120,0.261055,-81.877244
99,-0.722168,-1.128686,-0.427958,1.560704,-1.024388,1,-0.471038,-0.506943,-0.822220,0.243687,0.244967,-109.045266

In [27]:
# 병합(조인)
# on='target': 병합 기준 열
pd.merge(classification_df, blobs_df, on='target', how='inner')

,feature_1_x,feature_2_x,feature_3_x,feature_4_x,feature_5_x,target,feature_1_y,feature_2_y,feature_3_y,feature_4_y,feature_5_y
0,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,-3.002630,9.937449,6.346484,2.846759,-6.870483
1,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,-2.290559,9.896047,3.630793,0.389875,-6.105927
2,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,-3.463695,8.263107,3.509451,2.743147,-5.611238
3,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,-1.888649,8.853349,4.251614,1.087657,-7.236372
4,-0.430668,0.672873,-0.724280,-0.539630,-0.651600,0,-2.768226,8.439577,4.218381,2.312991,-6.887007
...,...,...,...,...,...,...,...,...,...,...,...
3345,-0.722168,-1.128686,-0.427958,1.560704,-1.024388,1,-7.117502,-6.966322,7.304081,1.089709,2.866509
3346,-0.722168,-1.128686,-0.427958,1.560704,-1.024388,1,-6.676287,-8.279219,8.196065,3.176655,3.684070
3347,-0.722168,-1.128686,-0.427958,1.560704,-1.024388,1,-5.902930,-8.796348,7.186251,1.898168,4.901792
3348,-0.722168,-1.128686,-0.427958,1.560704,-1.024388,1,-5.813911,-9.797336,8.705528,2.927422,3.557547
3349,-0.722168,-1.128686,-0.427958,1.560704,-1.024388,1,-8.777487,-7.557787,6.708389,4.133618,4.848300

## 데이터 탐색(EDA)

In [28]:
# 그룹별 평균
classification_df.groupby('target')[['feature_1', 'feature_2', 'feature_3']].mean()

        feature_1  feature_2  feature_3
target
0        0.070616   1.006369  -0.181439
1       -0.235811  -0.929705   0.083742

## 데이터 변환

In [29]:
blobs_df

    feature_1  feature_2  feature_3  feature_4  feature_5  target
0   -3.002630   9.937449   6.346484   2.846759  -6.870483       0
1   -5.970371  -9.040785   7.384420   2.669463   4.287546       1
2   -2.290559   9.896047   3.630793   0.389875  -6.105927       0
3   -3.463695   8.263107   3.509451   2.743147  -5.611238       0
4   -1.888649   8.853349   4.251614   1.087657  -7.236372       0
..        ...        ...        ...        ...        ...     ...
95  -5.813911  -9.797336   8.705528   2.927422   3.557547       1
96  -2.334365   7.797431   5.689226   3.298275  -6.145126       0
97  -3.138673   9.612007   7.199367   2.367403  -6.757408       0
98  -1.927075   9.902035   5.534211   2.728167  -7.086793       0
99  -8.777487  -7.557787   6.708389   4.133618   4.848300       1

[100 rows x 6 columns]

In [30]:
# 원-핫 인코딩
# prefix: 기본값은 열이름_순번
pd.get_dummies(blobs_df, columns=['target'], prefix='t')

    feature_1  feature_2  feature_3  feature_4  feature_5    t_0    t_1    t_2
0   -3.002630   9.937449   6.346484   2.846759  -6.870483   True  False  False
1   -5.970371  -9.040785   7.384420   2.669463   4.287546  False   True  False
2   -2.290559   9.896047   3.630793   0.389875  -6.105927   True  False  False
3   -3.463695   8.263107   3.509451   2.743147  -5.611238   True  False  False
4   -1.888649   8.853349   4.251614   1.087657  -7.236372   True  False  False
..        ...        ...        ...        ...        ...    ...    ...    ...
95  -5.813911  -9.797336   8.705528   2.927422   3.557547  False   True  False
96  -2.334365   7.797431   5.689226   3.298275  -6.145126   True  False  False
97  -3.138673   9.612007   7.199367   2.367403  -6.757408   True  False  False
98  -1.927075   9.902035   5.534211   2.728167  -7.086793   True  False  False
99  -8.777487  -7.557787   6.708389   4.133618   4.848300  False   True  False

[100 rows x 8 columns]

In [32]:
# feature_6 = feature_1 + feature_2
blobs_df['feature_6'] = blobs_df['feature_1'] + blobs_df['feature_2']

# feature_7 = (feature_3 + feature_4 + feature_5) / 3
blobs_df['feature_7'] = blobs_df[['feature_3', 'feature_4', 'feature_5']].mean(axis=1)

blobs_df

,feature_1,feature_2,feature_3,feature_4,feature_5,target,feature_6,feature_7
0,-3.002630,9.937449,6.346484,2.846759,-6.870483,0,6.934819,0.774253
1,-5.970371,-9.040785,7.384420,2.669463,4.287546,1,-15.011157,4.780476
2,-2.290559,9.896047,3.630793,0.389875,-6.105927,0,7.605488,-0.695086
3,-3.463695,8.263107,3.509451,2.743147,-5.611238,0,4.799412,0.213787
4,-1.888649,8.853349,4.251614,1.087657,-7.236372,0,6.964699,-0.632367
...,...,...,...,...,...,...,...,...
95,-5.813911,-9.797336,8.705528,2.927422,3.557547,1,-15.611247,5.063499
96,-2.334365,7.797431,5.689226,3.298275,-6.145126,0,5.463067,0.947458
97,-3.138673,9.612007,7.199367,2.367403,-6.757408,0,6.473334,0.936454
98,-1.927075,9.902035,5.534211,2.728167,-7.086793,0,7.974960,0.391862
99,-8.777487,-7.557787,6.708389,4.133618,4.848300,1,-16.335274,5.230102

In [33]:
# 정규화: 0~1 사이값으로 변환
scaler = MinMaxScaler()
regression_df[['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5']] = scaler.fit_transform(regression_df[['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5']])

regression_df

    feature_1  feature_2  feature_3  feature_4  feature_5      target
0    0.337543   0.087372   0.454642   0.095402   0.258324  -57.195760
1    0.253671   0.100928   0.635392   0.103853   0.233978  -46.546477
2    0.113374   0.071054   0.325728   0.087552   0.276894 -258.133440
3    0.185409   0.160796   0.775375   0.151451   0.330573  115.850751
4    0.187514   0.155096   0.000000   0.146033   0.298237 -123.767712
..        ...        ...        ...        ...        ...         ...
95   0.103745   0.075382   0.624853   0.188483   0.565936 -104.690611
96   0.173401   0.142139   0.363478   0.171561   0.253402  -49.838794
97   0.342790   0.178470   0.533468   0.130188   0.199704   97.685689
98   0.223956   0.135596   0.114507   0.176453   0.272751  -81.877244
99   0.201755   0.099403   0.264808   0.172892   0.271498 -109.045266

[95 rows x 6 columns]

In [36]:
# 표준화: 평균 0, 표준편차 1, 표준정규분포
scaler = StandardScaler()
classification_df[['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5']] = scaler.fit_transform(classification_df[['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5']])

classification_df

    feature_1  feature_2  feature_3  feature_4  feature_5  target
0   -0.417184   0.500431  -0.551841  -0.388604  -0.679322       0
1    0.352669  -0.695771   0.476848   0.647953   0.651310       1
2    1.408639   0.292411   0.938711  -0.694620  -1.008507       0
3    1.920696  -0.640143   1.672360   0.138801  -0.413618       0
4   -0.445031  -1.752229   0.239855   1.988092  -0.512322       1
..        ...        ...        ...        ...        ...     ...
95   0.981078   0.918648   0.381157  -1.230230  -0.180601       0
96   1.113093  -0.929708   1.150817   0.675390   0.599101       1
97  -0.913400   1.265677  -1.212807  -1.050652  -1.638332       0
98  -1.438451   0.064700  -1.186254   0.363089   2.088358       1
99  -0.766566  -0.920370  -0.309740   1.205795  -1.051292       1

[100 rows x 6 columns]

## 데이터 축소

In [37]:
# PCA(주성분 분석)
pca = PCA(n_components=3)
principal_components = pca.fit_transform(regression_df[['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5']])

principal_df = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2', 'PC3'])

principal_df

         PC1       PC2       PC3
0  -0.003711 -0.110848  0.004589
1   0.190682 -0.105595 -0.019945
2  -0.052895  0.033293 -0.201527
3   0.338315 -0.010324  0.006423
4  -0.392198  0.108551 -0.191479
..       ...       ...       ...
90  0.236814  0.198290 -0.011547
91 -0.044294  0.042818 -0.112054
92  0.056989 -0.128649  0.026225
93 -0.293304  0.074039 -0.125202
94 -0.140384  0.052866 -0.106494

[95 rows x 3 columns]

## 데이터 분할

In [38]:
classification_df

    feature_1  feature_2  feature_3  feature_4  feature_5  target
0   -0.417184   0.500431  -0.551841  -0.388604  -0.679322       0
1    0.352669  -0.695771   0.476848   0.647953   0.651310       1
2    1.408639   0.292411   0.938711  -0.694620  -1.008507       0
3    1.920696  -0.640143   1.672360   0.138801  -0.413618       0
4   -0.445031  -1.752229   0.239855   1.988092  -0.512322       1
..        ...        ...        ...        ...        ...     ...
95   0.981078   0.918648   0.381157  -1.230230  -0.180601       0
96   1.113093  -0.929708   1.150817   0.675390   0.599101       1
97  -0.913400   1.265677  -1.212807  -1.050652  -1.638332       0
98  -1.438451   0.064700  -1.186254   0.363089   2.088358       1
99  -0.766566  -0.920370  -0.309740   1.205795  -1.051292       1

[100 rows x 6 columns]

In [39]:
X = classification_df.drop(columns=['target'])
y = classification_df['target']

# 훈련 세트(Train Set)와 테스트 세트(Test Set) 두 개로 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(80, 5) (20, 5) (80,) (20,)